image: haskell:9

default:
  tags:
    - unwalled
    - docker

stages:
  - build

build:
  stage: build
  script:
    - stack setup
    - stack build
  cache:
    - key: stack-work-cache
      paths:
        - .stack-work/
    - key: stack-home-cache
      paths:
        - /root/.stack
