name:                hamodoro
version:             0.1.0.0
github:              "CSE230-FA21-Team/Hamodoro"
license:             BSD3
author:              "CSE 230 Team Members"
maintainer:          "hi@rongyi.xyz"
copyright:           "2021 Hamodoro Project Members"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Personal productivity timer written in Haskell

dependencies:
- base >= 4.7 && < 5
- aeson
- brick
- bytestring
- containers
- directory
- microlens
- random
- req
- text
- text-zipper
- time
- tomland
- vty

# NOTE: uncomment below to build brick-tac-toe
# internal-libraries:
#   libbtt:
#     source-dirs: src_btt

library:
  source-dirs: src

executables:
  hamodoro:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hamodoro
  # NOTE: uncomment below to build brick-tac-toe
  # brick-tac-toe:
  #   main:                Main_btt.hs
  #   source-dirs:         src_btt
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   # - hamodoro
  #   - libbtt

tests:
  hamodoro-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hamodoro
    # - brick-tac-toe
