on:
  push:
  pull_request:
  workflow_dispatch:

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Check formatting
        uses: mrkkrp/ormolu-action@v1

      - name: Set up hlint
        uses: rwe/actions-hlint-setup@v1
        with:
          version: "3.2.7"

      - name: Run hlint on src
        uses: rwe/actions-hlint-run@v2
        with:
          path: src/
          fail-on: error

      - name: Run hlint on src_btt
        uses: rwe/actions-hlint-run@v2
        with:
          path: src_btt/
          fail-on: error

      - name: Cache ~/.stack folder
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: stack-global-linux-${{hashFiles('**.yaml')}}
          restore-keys: |
            stack-global-linux

      - name: Cache ~/.local/bin folder
        uses: actions/cache@v2
        with:
          path: ~/.local/bin
          key: stack-local-bin-linux-${{hashFiles('**.yaml')}}
          restore-keys: |
            stack-local-bin-linux

      - name: Cache .stack-work folder
        uses: actions/cache@v2
        with:
          path: .stack-work
          key: stack-work-linux-${{hashFiles('**.yaml')}}
          restore-keys: |
            stack-work-linux

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: "8.10.7" # Exact version of ghc to use
          enable-stack: true
          stack-version: "latest"

      - name: Build project
        run: |
          stack build

      - name: Run tests
        run: |
          stack test --fast
